### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by ishandeveloper** [smaranjitghose/Binod_Spam_Filter#1]
### How about creating a web browser extension 
that can filter out '**BINOD**' on every single web page out there and replace it with *this* ██████  instead ? 😉

I can work on this, if you'd like 😂🤘🏻

**Comment by smaranjitghose** [comment]
> ### How about creating a web browser extension
> that can filter out '**BINOD**' on every single web page out there and replace it with _this_ ██████ instead ? 😉
> 
> I can work on this, if you'd like 😂🤘🏻

Haha that sounds awesome @ishandeveloper ! I look forward to seeing how cool you can make it. Maybe instead of the blacked one we can put an emoji llike 🤷‍♂️
